# This file configures how the docs are built.
#
# This defines the theme to use to build and style the docs.
#   The value requires a valid Jekyll theme that is stored in a 
#     publicly available GitHub repo.
#     The format for this property's value is <GitHub account>/<repo> 
remote_theme: just-the-docs/just-the-docs
#   For information about this theme and its options, see: https://just-the-docs.com/
#
# These values describe aspects of the final documentation. How they are
# applied depends on the theme that is in use.
title: Flexigift Service
description: Documentation of the Flexigift service API
url: https://dougmanis.github.io/flexigift-service/
aux_links: # remove if you don't want this link to appear on your pages
  Service repo: https://github.com/dougmanis/flexigift-service
permalink: pretty
